version: "3.3"
services:

    web:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: finlex_restapi
        depends_on:
            - db
        volumes:
            - ./:/usr/src/app
        ports:
            - 3000:3000

    db:
        container_name: finlex_db
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: robot-db
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - 3307:3306

    # jenkins:
    #     image: jenkins/jenkins
    #     container_name: jenkins
    #     user: jenkins
    #     volumes:
    #         - ./yjenkins/:/var/jenkins_home
    #     environment:
    #         JENKINS_HOST_HOME: "./yjenkins/"
    #     ports:
    #         - "8080:8080"
    #         - "5000:5000"
    #         - "50000:50000"